### ISSUE TITLE
Using this index system 

### ISSUE THREAD

**Issue by neosaldina** [andrerav/Geohash.SpatialIndex#2]
I'm developing a system, where I have a list of 100,000 geolocations and 10,000 geolocations of cars that are moving, and every X seconds, the vehicle's location update occurs, that is, at the same time I can receive N vehicle location updates .
My problem is, every X seconds, the system needs to search for all vehicles that are close to a location L, currently, the system goes through the list of geolocations looking for all vehicles that are within the specific radius.

My doubt is whether it is possible to use this lib, and the index part of it, to reduce the overhead in this process of searching vehicles near a location L, and, it is thread safe ?
Thanks

**Comment by andrerav** [comment]
Hi @neosaldina! Sorry for the late reply! Holy smokes this sounds like a great application for this library. In fact I built it with maritime vessel traffic in mind :) Based on your description I think it definitely should be possible to speed up your current solution. With regards to thread safety I think you should be able to get by with some simple locks. If you want we can schedule a chat on teams and discuss specific technical details? I'd really love to help you out with this! :)

**Comment by andrerav** [comment]
@neosaldina Did you find another solution? :)
